apiVersion: v1
kind: Service
metadata:
  name: interview-companion-service
spec:
  type: NodePort
  selector:
    app: interview-companion
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30081
